[package]
name = "yaydl"
version = "0.3.0"
description = "Yet Another YouTube Downloader"
authors = ["NiklasRhf <65732627+niklasrhf@users.noreply.github.com>"]
edition = "2021"
license = "MIT"

[lib]
name = "yaydl_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
zip = "8.6.0"
tar = "0.4.46"
xz2 = "0.1.7"
reqwest = { version = "0.13.5", features = ["blocking"] }
sha2 = "0.11.0"

[dependencies]
dirs = "7.0.0"
jiff = "0.2.37"
serde = { workspace = true }
yaydl-shared = { workspace = true }
serde_json = "1.0.151"
sys-locale = "0.3.2"
tauri = { version = "2.11.6", features = [] }
tauri-plugin-clipboard-manager = "2.3.3"
tauri-plugin-dialog = "2.7.3"
tauri-plugin-notification = "2.4.0"
tauri-plugin-opener = "2.5.5"
tokio = { version = "1.53.1", features = ["io-util", "process", "sync", "time", "macros", "rt"] }
tokio-util = "0.7.19"
toml = "1.1.6"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
url = "2.5.8"

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[dev-dependencies]
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["macros", "rt", "rt-multi-thread", "test-util"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.12.0"
