//! Wire types shared by the Tauri backend and the Leptos webview. Everything here
//! crosses the IPC boundary as JSON, and `Settings` is also persisted as TOML.

use std::{fmt, path::PathBuf};

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Generated by the backend when an item is added. Not the video id, which is
/// unknown until metadata has been resolved.
pub type DownloadId = u64;

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

pub const SETTINGS_VERSION: u32 = 3;
pub const MAX_CONCURRENT_DOWNLOADS: u8 = 5;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Settings {
    pub version: u32,
    pub output_dir: PathBuf,
    pub default_format: OutputFormat,
    pub theme: Theme,
    pub yt_dlp_channel: YtDlpChannel,
    pub max_concurrent_downloads: u8,
    pub embed_metadata: bool,
    pub notify_on_finish: bool,
    pub cookies_from_browser: Option<Browser>,
    pub language: Language,
}

impl Settings {
    /// Checks everything that does not need the filesystem. The backend also
    /// checks that `output_dir` is an existing directory.
    pub fn validate(&self) -> Result<(), String> {
        if self.version != SETTINGS_VERSION {
            return Err(format!(
                "settings version is {}, expected {SETTINGS_VERSION}",
                self.version
            ));
        }
        if !(1..=MAX_CONCURRENT_DOWNLOADS).contains(&self.max_concurrent_downloads) {
            return Err(format!(
                "max_concurrent_downloads is {}, expected 1 to {MAX_CONCURRENT_DOWNLOADS}",
                self.max_concurrent_downloads
            ));
        }
        if self.output_dir.as_os_str().is_empty() {
            return Err("output_dir is empty".to_string());
        }
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum OutputFormat {
    Audio { codec: AudioCodec },
    Video { quality: VideoQuality },
}

impl OutputFormat {
    /// Part of the duplicate-detection key, together with extractor and video id.
    pub fn key(&self) -> String {
        match self {
            OutputFormat::Audio { codec } => format!("audio:{}", codec.as_str()),
            OutputFormat::Video { quality } => format!("video:{}", quality.as_str()),
        }
    }

    pub fn all() -> Vec<OutputFormat> {
        AudioCodec::ALL
            .into_iter()
            .map(|codec| OutputFormat::Audio { codec })
            .chain(
                VideoQuality::ALL
                    .into_iter()
                    .map(|quality| OutputFormat::Video { quality }),
            )
            .collect()
    }

    pub fn parse_key(key: &str) -> Option<OutputFormat> {
        OutputFormat::all().into_iter().find(|f| f.key() == key)
    }
}

impl fmt::Display for OutputFormat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            OutputFormat::Audio { codec } => write!(f, "{} audio", codec.label()),
            OutputFormat::Video { quality } => write!(f, "MP4 video {}", quality.label()),
        }
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum AudioCodec {
    Mp3,
    M4a,
    Opus,
    Flac,
}

impl AudioCodec {
    pub const ALL: [AudioCodec; 4] = [
        AudioCodec::Mp3,
        AudioCodec::M4a,
        AudioCodec::Opus,
        AudioCodec::Flac,
    ];

    /// The value yt-dlp expects for `--audio-format`.
    pub fn as_str(self) -> &'static str {
        match self {
            AudioCodec::Mp3 => "mp3",
            AudioCodec::M4a => "m4a",
            AudioCodec::Opus => "opus",
            AudioCodec::Flac => "flac",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            AudioCodec::Mp3 => "MP3",
            AudioCodec::M4a => "M4A",
            AudioCodec::Opus => "Opus",
            AudioCodec::Flac => "FLAC",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        AudioCodec::ALL.into_iter().find(|c| c.as_str() == value)
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VideoQuality {
    #[serde(rename = "best")]
    Best,
    #[serde(rename = "1080p")]
    P1080,
    #[serde(rename = "720p")]
    P720,
    #[serde(rename = "480p")]
    P480,
}

impl VideoQuality {
    pub const ALL: [VideoQuality; 4] = [
        VideoQuality::Best,
        VideoQuality::P1080,
        VideoQuality::P720,
        VideoQuality::P480,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            VideoQuality::Best => "best",
            VideoQuality::P1080 => "1080p",
            VideoQuality::P720 => "720p",
            VideoQuality::P480 => "480p",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            VideoQuality::Best => "best",
            VideoQuality::P1080 => "1080p",
            VideoQuality::P720 => "720p",
            VideoQuality::P480 => "480p",
        }
    }

    pub fn max_height(self) -> Option<u32> {
        match self {
            VideoQuality::Best => None,
            VideoQuality::P1080 => Some(1080),
            VideoQuality::P720 => Some(720),
            VideoQuality::P480 => Some(480),
        }
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum Theme {
    #[default]
    System,
    Light,
    Dark,
}

impl Theme {
    pub const ALL: [Theme; 3] = [Theme::System, Theme::Light, Theme::Dark];

    pub fn as_str(self) -> &'static str {
        match self {
            Theme::System => "system",
            Theme::Light => "light",
            Theme::Dark => "dark",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Theme::ALL.into_iter().find(|t| t.as_str() == value)
    }
}

/// The user's choice. `System` follows the OS locale, see [`Language::resolve`].
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum Language {
    #[default]
    System,
    English,
    German,
}

/// The language texts are actually rendered in.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Locale {
    En,
    De,
}

impl Language {
    pub const ALL: [Language; 3] = [Language::System, Language::English, Language::German];

    pub fn as_str(self) -> &'static str {
        match self {
            Language::System => "system",
            Language::English => "english",
            Language::German => "german",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Language::ALL.into_iter().find(|l| l.as_str() == value)
    }

    /// `system_tag` is a BCP 47 tag such as `de-AT` (the webview's
    /// `navigator.language`, the backend's OS locale). Only German has a
    /// translation, every other system language renders English.
    pub fn resolve(self, system_tag: Option<&str>) -> Locale {
        match self {
            Language::English => Locale::En,
            Language::German => Locale::De,
            Language::System => match system_tag {
                Some(tag) if tag.to_ascii_lowercase().starts_with("de") => Locale::De,
                _ => Locale::En,
            },
        }
    }
}

/// Browsers yt-dlp can read cookies from via `--cookies-from-browser`.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Browser {
    Brave,
    Chrome,
    Chromium,
    Edge,
    Firefox,
    Opera,
    Safari,
    Vivaldi,
    Whale,
}

impl Browser {
    pub const ALL: [Browser; 9] = [
        Browser::Brave,
        Browser::Chrome,
        Browser::Chromium,
        Browser::Edge,
        Browser::Firefox,
        Browser::Opera,
        Browser::Safari,
        Browser::Vivaldi,
        Browser::Whale,
    ];

    /// The value yt-dlp expects for `--cookies-from-browser`.
    pub fn as_str(self) -> &'static str {
        match self {
            Browser::Brave => "brave",
            Browser::Chrome => "chrome",
            Browser::Chromium => "chromium",
            Browser::Edge => "edge",
            Browser::Firefox => "firefox",
            Browser::Opera => "opera",
            Browser::Safari => "safari",
            Browser::Vivaldi => "vivaldi",
            Browser::Whale => "whale",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Browser::ALL.into_iter().find(|b| b.as_str() == value)
    }
}

/// yt-dlp release channel passed to `yt-dlp --update-to <channel>`.
/// Nightly is the default because YouTube extractor fixes land there days
/// before a stable release.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum YtDlpChannel {
    Stable,
    #[default]
    Nightly,
}

impl YtDlpChannel {
    pub const ALL: [YtDlpChannel; 2] = [YtDlpChannel::Stable, YtDlpChannel::Nightly];

    pub fn as_str(self) -> &'static str {
        match self {
            YtDlpChannel::Stable => "stable",
            YtDlpChannel::Nightly => "nightly",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        YtDlpChannel::ALL.into_iter().find(|c| c.as_str() == value)
    }
}

impl fmt::Display for YtDlpChannel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Queue
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct VideoMetadata {
    /// yt-dlp's `extractor_key` (or `ie_key` for flat playlist entries), e.g. `Youtube`.
    pub extractor: String,
    pub video_id: String,
    pub title: String,
    pub uploader: Option<String>,
    pub duration_secs: Option<f64>,
    pub thumbnail: Option<String>,
    pub webpage_url: String,
}

impl VideoMetadata {
    /// Same video in the same output format means the same file.
    pub fn duplicate_key(&self, format: &OutputFormat) -> String {
        format!(
            "{}|{}|{}",
            self.extractor.to_lowercase(),
            self.video_id,
            format.key()
        )
    }
}

/// An earlier finished download of the same video in the same format whose file
/// still exists on disk.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct PreviousDownload {
    pub finished_at_ms: i64,
    pub file_path: PathBuf,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DownloadItem {
    pub id: DownloadId,
    pub url: String,
    pub added_at_ms: i64,
    pub metadata: Option<VideoMetadata>,
    pub format: OutputFormat,
    /// File name without extension chosen by the user, validated with
    /// [`validate_file_stem`]. `None` uses the default `<title> [<id>]`.
    pub custom_name: Option<String>,
    pub status: DownloadStatus,
    pub previous_download: Option<PreviousDownload>,
    /// Final file, set once the item is `Finished`.
    pub file_path: Option<PathBuf>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(tag = "state", rename_all = "snake_case")]
pub enum DownloadStatus {
    ResolvingMetadata,
    MetadataFailed {
        error: FriendlyError,
    },
    Ready,
    /// The user started a download that matches an earlier one; waits for
    /// `confirm_duplicate`.
    AwaitingDuplicateConfirmation,
    /// Waiting for a free concurrency slot.
    Queued,
    Downloading {
        progress: Progress,
    },
    /// ffmpeg post-processing (extract audio, merge, embed tags).
    Processing,
    Finished,
    Failed {
        error: FriendlyError,
    },
    Cancelled,
}

impl DownloadStatus {
    pub fn name(&self) -> &'static str {
        match self {
            DownloadStatus::ResolvingMetadata => "resolving metadata",
            DownloadStatus::MetadataFailed { .. } => "missing metadata",
            DownloadStatus::Ready => "ready",
            DownloadStatus::AwaitingDuplicateConfirmation => "awaiting confirmation",
            DownloadStatus::Queued => "queued",
            DownloadStatus::Downloading { .. } => "downloading",
            DownloadStatus::Processing => "processing",
            DownloadStatus::Finished => "finished",
            DownloadStatus::Failed { .. } => "failed",
            DownloadStatus::Cancelled => "cancelled",
        }
    }

    /// Holds a concurrency slot or is waiting for one. Cannot be removed or edited.
    pub fn is_active(&self) -> bool {
        matches!(
            self,
            DownloadStatus::Queued
                | DownloadStatus::Downloading { .. }
                | DownloadStatus::Processing
        )
    }

    pub fn can_start(&self) -> bool {
        matches!(self, DownloadStatus::Ready)
    }

    pub fn can_retry(&self) -> bool {
        matches!(
            self,
            DownloadStatus::Failed { .. }
                | DownloadStatus::Cancelled
                | DownloadStatus::MetadataFailed { .. }
        )
    }

    pub fn can_cancel(&self) -> bool {
        self.is_active() || matches!(self, DownloadStatus::AwaitingDuplicateConfirmation)
    }

    /// Format and name can change until the download starts.
    pub fn can_edit_before_download(&self) -> bool {
        matches!(
            self,
            DownloadStatus::Ready
                | DownloadStatus::MetadataFailed { .. }
                | DownloadStatus::Failed { .. }
                | DownloadStatus::Cancelled
        )
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
pub struct Progress {
    pub percent: Option<f32>,
    pub downloaded_bytes: Option<u64>,
    pub total_bytes: Option<u64>,
    pub speed_bytes_per_sec: Option<f64>,
    pub eta_secs: Option<u64>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct FriendlyError {
    pub kind: ErrorKind,
    /// One or two sentences for the user, including what to do next.
    pub message: String,
    /// Raw tail of yt-dlp's stderr or the underlying error, for "show details".
    pub detail: String,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ErrorKind {
    AgeRestricted,
    BotCheck,
    Private,
    Unavailable,
    GeoBlocked,
    RateLimited,
    Network,
    UnsupportedUrl,
    NotYetLive,
    DiskFull,
    /// The app exited while the download was running.
    Interrupted,
    /// The configured output folder does not exist. `detail` holds the path.
    OutputFolderMissing,
    /// A playlist resolved to no downloadable entries.
    EmptyPlaylist,
    Other,
}

impl ErrorKind {
    /// Errors that browser cookies (`cookies_from_browser`) usually fix.
    pub fn suggests_cookies(self) -> bool {
        matches!(
            self,
            ErrorKind::AgeRestricted | ErrorKind::BotCheck | ErrorKind::Private
        )
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
pub struct AddUrlsResult {
    pub added: Vec<DownloadId>,
    /// URLs already in the queue, skipped.
    pub already_queued: Vec<String>,
    /// Tokens that were not http(s) URLs.
    pub invalid: Vec<String>,
}

/// The playlist named by a link to a single video.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlaylistLink {
    pub list_id: String,
    /// YouTube Mixes (`RD…`) are generated per viewer and have no playlist
    /// page, so they can only be expanded from a video link.
    pub is_mix: bool,
}

/// A YouTube link to one video that also names the playlist it was opened
/// from, e.g. `watch?v=X&list=Y`. yaydl adds only the video from such a link
/// until the user asks for the whole playlist (`expand_playlist`).
pub fn playlist_in_video_link(link: &str) -> Option<PlaylistLink> {
    let url = url::Url::parse(link).ok()?;
    let host = url.host_str()?;
    let host = host.strip_prefix("www.").unwrap_or(host);
    let query_value = |key: &str| {
        url.query_pairs()
            .find(|(k, v)| k == key && !v.is_empty())
            .map(|(_, v)| v.into_owned())
    };
    let names_video = match host {
        "youtube.com" | "m.youtube.com" | "music.youtube.com" => {
            url.path() == "/watch" && query_value("v").is_some()
        }
        "youtu.be" => url.path().len() > 1,
        _ => false,
    };
    if !names_video {
        return None;
    }
    let list_id = query_value("list")?;
    Some(PlaylistLink {
        is_mix: list_id.starts_with("RD"),
        list_id,
    })
}

const FORBIDDEN_FILE_CHARS: [char; 9] = ['/', '\\', ':', '*', '?', '"', '<', '>', '|'];
const RESERVED_WINDOWS_NAMES: [&str; 22] = [
    "CON", "PRN", "AUX", "NUL", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8",
    "COM9", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9",
];
pub const MAX_FILE_STEM_CHARS: usize = 200;

/// Validates a user-chosen file name without extension. Rejects rather than
/// rewrites, so the name on disk is exactly what the user typed. The rules are
/// the union of Linux and Windows restrictions, so a name valid here is valid
/// on both.
pub fn validate_file_stem(name: &str) -> Result<(), String> {
    if name.trim().is_empty() {
        return Err("the name is empty".to_string());
    }
    if name != name.trim() {
        return Err("the name starts or ends with whitespace".to_string());
    }
    if name.ends_with('.') {
        return Err("the name ends with a dot".to_string());
    }
    if name.chars().count() > MAX_FILE_STEM_CHARS {
        return Err(format!(
            "the name is longer than {MAX_FILE_STEM_CHARS} characters"
        ));
    }
    if let Some(c) = name
        .chars()
        .find(|c| FORBIDDEN_FILE_CHARS.contains(c) || c.is_control())
    {
        return Err(format!("the name contains the forbidden character {c:?}"));
    }
    let base = name.split('.').next().unwrap_or(name).to_ascii_uppercase();
    if RESERVED_WINDOWS_NAMES.contains(&base.as_str()) {
        return Err(format!("\"{name}\" is a reserved name on Windows"));
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// History and statistics
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct HistoryEntry {
    pub download_id: DownloadId,
    pub extractor: String,
    pub video_id: String,
    pub title: String,
    pub uploader: Option<String>,
    pub url: String,
    pub format: OutputFormat,
    pub file_path: PathBuf,
    pub file_size_bytes: Option<u64>,
    pub duration_secs: Option<f64>,
    pub finished_at_ms: i64,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum StatsGranularity {
    /// The last 30 days.
    Day,
    /// The last 12 ISO weeks, Monday first.
    Week,
    /// The last 12 calendar months.
    Month,
}

impl StatsGranularity {
    pub const ALL: [StatsGranularity; 3] = [
        StatsGranularity::Day,
        StatsGranularity::Week,
        StatsGranularity::Month,
    ];

    pub fn bucket_count(self) -> usize {
        match self {
            StatsGranularity::Day => 30,
            StatsGranularity::Week => 12,
            StatsGranularity::Month => 12,
        }
    }
}

/// All times are in the system's local time zone.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Statistics {
    pub granularity: StatsGranularity,
    /// Oldest first, zero-filled, the last bucket is the current period.
    pub buckets: Vec<StatsBucket>,
    pub totals: StatsTotals,
    /// `activity[weekday][hour]`, weekday 0 is Monday. Always 7 rows.
    pub activity: Vec<[u32; 24]>,
    /// 0 is Monday. `None` without history.
    pub busiest_weekday: Option<u8>,
    pub busiest_hour: Option<u8>,
    pub busiest_day: Option<DayCount>,
    /// Consecutive days with at least one download, ending today or yesterday.
    pub current_streak_days: u32,
    pub longest_streak_days: u32,
    /// Top 5 by count, ties broken by name.
    pub top_uploaders: Vec<NameCount>,
    /// By `OutputFormat` display name, most used first.
    pub formats: Vec<NameCount>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct StatsBucket {
    /// First day of the bucket, `YYYY-MM-DD`. The UI derives localized labels
    /// from it and the granularity.
    pub start_date: String,
    pub count: u32,
    pub bytes: u64,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
pub struct StatsTotals {
    pub downloads: u32,
    pub bytes: u64,
    pub duration_secs: f64,
    pub distinct_uploaders: u32,
    pub first_download_ms: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct DayCount {
    /// `YYYY-MM-DD`
    pub date: String,
    pub count: u32,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct NameCount {
    pub name: String,
    pub count: u32,
}

// ---------------------------------------------------------------------------
// yt-dlp and app updates
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct YtDlpStatus {
    pub version: String,
    pub channel: YtDlpChannel,
    pub binary_path: String,
}

/// Result of a yt-dlp self-update, returned by the `update_yt_dlp` command.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum YtDlpUpdateEvent {
    Updated {
        from: String,
        to: String,
        channel: YtDlpChannel,
    },
    AlreadyCurrent {
        version: String,
        channel: YtDlpChannel,
    },
    Failed {
        message: String,
    },
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct AppUpdateInfo {
    pub current_version: String,
    pub version: String,
    pub notes: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct AppInfo {
    pub version: String,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct AppUpdateProgress {
    pub downloaded_bytes: u64,
    pub total_bytes: Option<u64>,
}

// ---------------------------------------------------------------------------
// Notices and events
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum NoticeLevel {
    Info,
    Success,
    Warning,
    Error,
}

/// A message the backend wants the user to see as a toast. Notices raised
/// before the webview called `take_startup_notices` are buffered and returned
/// by that call, later ones are emitted as the `notice` event.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct Notice {
    pub level: NoticeLevel,
    pub text: String,
}

/// Event names emitted by the backend. Tauri wraps each payload in
/// `{ event, id, payload }`.
pub mod events {
    /// Payload `Vec<DownloadItem>`, the whole queue in display order. Sent on
    /// structural changes (add, remove, clear, playlist expansion).
    pub const QUEUE_REPLACED: &str = "queue-replaced";
    /// Payload `DownloadItem`. Sent when a single item changes, progress
    /// included, at most a few times per second per item.
    pub const QUEUE_ITEM_UPDATED: &str = "queue-item-updated";
    /// Payload `Notice`.
    pub const NOTICE: &str = "notice";
    /// Payload `AppUpdateProgress`.
    pub const APP_UPDATE_PROGRESS: &str = "app-update-progress";
    /// Payload `()`. Emitted when history changed (a download finished, a
    /// rename, or clear), so an open statistics view can reload.
    pub const HISTORY_CHANGED: &str = "history-changed";
}

// ---------------------------------------------------------------------------
// Command arguments. Tauri matches command arguments by camelCase name.
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IdArgs {
    pub id: DownloadId,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AddUrlsArgs {
    pub text: String,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfirmDuplicateArgs {
    pub id: DownloadId,
    pub proceed: bool,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetFormatArgs {
    pub id: DownloadId,
    pub format: OutputFormat,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RenameArgs {
    pub id: DownloadId,
    pub name: String,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StatsArgs {
    pub granularity: StatsGranularity,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SettingsArgs {
    pub settings: Settings,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LogArgs<'a> {
    pub level: &'a str,
    pub message: String,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecentLogsArgs {
    pub max_lines: usize,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClipboardArgs {
    pub text: String,
}

/// The tail of the current log file, for the in-app log viewer.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct LogSnapshot {
    pub path: String,
    pub app_version: String,
    pub lines: Vec<String>,
    /// `true` when the file had more lines than were returned.
    pub truncated: bool,
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Error, Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum YtDlpError {
    #[error("yt-dlp failed (exit code {exit_code:?}): {stderr}")]
    CommandFailed {
        exit_code: Option<i32>,
        stderr: String,
    },
    #[error("yt-dlp update to {channel} failed: {stderr}")]
    UpdateFailed {
        channel: YtDlpChannel,
        stderr: String,
    },
    #[error("installing bundled yt-dlp failed: {0}")]
    Bootstrap(String),
    #[error("yt-dlp state file is invalid: {0}")]
    InvalidState(String),
    /// Kept apart from `CommandFailed` because a failure to even run yt-dlp is
    /// not something a yt-dlp update can repair.
    #[error("yt-dlp I/O error: {0}")]
    Io(String),
}

#[derive(Error, Serialize, Deserialize, Debug, Clone, PartialEq)]
pub enum YaydlError {
    #[error(transparent)]
    YtDlp(#[from] YtDlpError),
    #[error("No download with id {0}")]
    UnknownDownload(DownloadId),
    #[error("Cannot {action} a download that is {state}")]
    InvalidState { action: String, state: String },
    #[error("Invalid file name: {0}")]
    InvalidFileName(String),
    #[error("Invalid settings: {0}")]
    InvalidSettings(String),
    #[error("{0}")]
    Io(String),
    #[error("Reading the clipboard failed: {0}")]
    ClipboardRead(String),
    #[error("Writing to the clipboard failed: {0}")]
    ClipboardWrite(String),
    #[error("Opening failed: {0}")]
    Open(String),
    #[error("App update failed: {0}")]
    AppUpdate(String),
    #[error("Saving failed: {0}")]
    Persist(String),
    #[error("Unknown log level \"{0}\"")]
    UnknownLogLevel(String),
    #[error("Reading the log file failed: {0}")]
    LogsUnavailable(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_stem_validation() {
        assert!(validate_file_stem("My Song (live)").is_ok());
        assert!(validate_file_stem("Ünïcödé 日本").is_ok());
        for bad in [
            "", "  ", " lead", "trail ", "a/b", "a\\b", "what?", "end.", "CON", "con.txt",
            "a\u{7}b",
        ] {
            assert!(
                validate_file_stem(bad).is_err(),
                "{bad:?} should be rejected"
            );
        }
        assert!(validate_file_stem(&"x".repeat(MAX_FILE_STEM_CHARS + 1)).is_err());
    }

    #[test]
    fn system_language_resolves_from_the_tag() {
        assert_eq!(Language::System.resolve(Some("de-AT")), Locale::De);
        assert_eq!(Language::System.resolve(Some("DE")), Locale::De);
        assert_eq!(Language::System.resolve(Some("en-US")), Locale::En);
        assert_eq!(Language::System.resolve(Some("fr-FR")), Locale::En);
        assert_eq!(Language::System.resolve(None), Locale::En);
        assert_eq!(Language::German.resolve(Some("en-US")), Locale::De);
        assert_eq!(Language::English.resolve(Some("de-DE")), Locale::En);
    }

    #[test]
    fn playlist_links_are_detected_only_on_video_links() {
        let pl = playlist_in_video_link(
            "https://www.youtube.com/watch?v=viuYLuyILeo&list=PLhCCfdELbr0Pi9RLMNAGhzKyF50LqlB4U",
        )
        .unwrap();
        assert_eq!(pl.list_id, "PLhCCfdELbr0Pi9RLMNAGhzKyF50LqlB4U");
        assert!(!pl.is_mix);
        let mix = playlist_in_video_link(
            "https://www.youtube.com/watch?v=onVL3uQD8UY&list=RDyrc0yef1xoU&index=4",
        )
        .unwrap();
        assert!(mix.is_mix);
        assert!(playlist_in_video_link("https://youtu.be/abc?list=PLx").is_some());
        assert!(playlist_in_video_link("https://music.youtube.com/watch?v=a&list=OLx").is_some());
        for none in [
            "https://www.youtube.com/playlist?list=PLx",
            "https://www.youtube.com/watch?v=abc",
            "https://www.youtube.com/watch?v=abc&list=",
            "https://vimeo.com/watch?v=abc&list=PLx",
            "not a url",
        ] {
            assert_eq!(playlist_in_video_link(none), None, "{none}");
        }
    }

    #[test]
    fn format_keys_round_trip() {
        for format in OutputFormat::all() {
            assert_eq!(OutputFormat::parse_key(&format.key()), Some(format));
        }
    }
}
